

# A Source contains attributes of a sequence of bytes, called symbols.
#
class Source

    # Analyze sequence generated by `symbols.each_byte'.
    #
    def initialize(symbols)
        freq = @frequencies = Hash.new(0)
        prob = @probabilities = Hash.new
        symbols.each_byte { |symbol| freq[symbol.chr] += 1 }
        @length = freq.values.reduce(:+)
        freq.each { |symbol, n| prob[symbol] = n / @length.to_f }
        @entropy = prob.values.inject(0){ |sum, p| sum - p * Math.log2(p) }
    end

    # The frequency distribution of symbols.
    attr_reader :frequencies

    # The empirical probability distribution of symbols.
    attr_reader :probabilities

    # The entropy of the probability distribution.
    attr_reader :entropy

    # The length of the given sequence of symbols.
    attr_reader :length
end
